# Generated by Django 6.1.1 on 2026-10-06 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('footer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacts',
            name='country',
            field=models.CharField(blank=True, max_length=100, verbose_name='Страна регистрации'),
        ),
        migrations.AddField(
            model_name='contacts',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email для обращений и персональных данных'),
        ),
        migrations.AddField(
            model_name='contacts',
            name='legal_address',
            field=models.TextField(blank=True, verbose_name='Юридический адрес'),
        ),
        migrations.AddField(
            model_name='contacts',
            name='registration_number',
            field=models.CharField(blank=True, max_length=100, verbose_name='Регистрационный номер'),
        ),
        migrations.AddField(
            model_name='contacts',
            name='seller_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Наименование продавца / ФИО ИП'),
        ),
        migrations.AddField(
            model_name='contacts',
            name='tax_id',
            field=models.CharField(blank=True, max_length=100, verbose_name='ИНН / налоговый номер'),
        ),
        migrations.AlterField(
            model_name='infopage',
            name='content',
            field=models.TextField(blank=True, help_text='Обычный текст; заголовки разделов начинайте с ##. HTML не исполняется.', verbose_name='Контент'),
        ),
        migrations.AlterField(
            model_name='infopage',
            name='page_type',
            field=models.CharField(choices=[('cookies', 'Политика cookie'), ('delivery', 'Доставка'), ('payment', 'Оплата'), ('returns', 'Возврат и обмен'), ('contacts', 'Контакты и реквизиты'), ('payment_return', 'Оплата и возврат'), ('documents', 'Документы'), ('privacy', 'Политика конфиденциальности'), ('terms', 'Условия покупки и использования')], max_length=20, unique=True, verbose_name='Тип страницы'),
        ),
    ]
